id: P251E1D9C
initial_creation_type: ocr
source_metadata:
  volumes:
    d31f6ad8769c4f37b5575b7ed81b0729:
      base_file: v067.txt
      image_group_id: I1PD95912
      title: འཕགས་པ་བཟང་པོ་སྤྱོད་པའི་སྨོན་ལམ་གྱི་འགྲེལ་པ།
      total_pages: 1529
      volume_number: 67
